title: Send SMS Message in .NET
# external_link: https://www.nexmo.com/blog/2017/03/23/send-sms-messages-asp-net-mvc-framework-dr/
products:
 - messaging/sms
description: Enhance your .NET application by adding the ability to send SMS messages to users. This tutorial walks you through adding a simple form to your web application, and sending an SMS message to the number provided.
languages:
  - dotnet

introduction:
  title: Introduction to this task
  description: This task shows you how to send an SMS message from a simple ASP.NET MVC web form
  content: |
    # Introduction
    In this tutorial, we will learn how to send an SMS message from a simple ASP.NET core application.
  
prerequisites:
- create-nexmo-account
- create-mvc-app

tasks:
  - install-nexmo-nuget-package
  - messaging/dotnet/create-sms-view
  - messaging/dotnet/add-send-sms-form
  - messaging/dotnet/create-sms-controller
  - messaging/dotnet/add-nexmo-using-statements
  - messaging/dotnet/add-send-sms-action
  - messaging/dotnet/send-sms


conclusion:
  title: What's next?
  description: What else can you do with the Nexmo .NET SDK?
  content: |

    # What's next?
    There's an awful lot you can do with the Nexmo .NET SDK Including.

    * Receiving SMS
    * Making & receiving phone calls (both PSTN/SIP)
    * Creating conference calls
    * Setting up IVRs
    * Preforming 2-FA over SMS / phone
    * Gaining Number Insights
    * And much more

    We want to hear what ideas you have in mind? Contact us at [devrel@nexmo.com](mailto:devrel@nexmo.com)
        